apiVersion: v1
kind: Secret
metadata:
  name: clearml-conf
data:
  apiserver_key: {{ if .Values.clearml.apiserverKey }}{{ .Values.clearml.apiserverKey | b64enc | quote }}{{ else }}{{ randAlpha 20 | upper | b64enc | quote }}{{ end }}
  apiserver_secret: {{ if .Values.clearml.apiserverSecret }}{{ .Values.clearml.apiserverSecret | b64enc | quote }}{{ else }}{{ randAlpha 49 | upper | b64enc | quote }}{{ end }}
  fileserver_key: {{ if .Values.clearml.fileserverKey }}{{ .Values.clearml.fileserverKey | b64enc | quote }}{{ else }}{{ randAlpha 20 | upper | b64enc | quote }}{{ end }}
  fileserver_secret: {{ if .Values.clearml.fileserverSecret }}{{ .Values.clearml.fileserverSecret | b64enc | quote }}{{ else }}{{ randAlpha 49 | upper | b64enc | quote }}{{ end }}
  secure_auth_token_secret: {{ if .Values.clearml.secureAuthTokenSecret }}{{ .Values.clearml.secureAuthTokenSecret | b64enc | quote }}{{ else }}{{ randAlpha 50 | b64enc | quote }}{{ end }}
  test_user_key: {{ if .Values.clearml.testUserKey }}{{ .Values.clearml.testUserKey | b64enc | quote }}{{ else }}{{ randAlpha 20 | upper | b64enc | quote }}{{ end }}
  test_user_secret: {{ if .Values.clearml.testUserSecret }}{{ .Values.clearml.testUserSecret | b64enc | quote }}{{ else }}{{ randAlpha 50 | upper | b64enc | quote }}{{ end }}
---
{{- if .Values.imageCredentials.enabled }}
{{- if not .Values.imageCredentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: clearml-registry-key
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
{{- end }}
